.PHONY: all clean

all:
	g++ sub1.cpp -o sub1 -std=c++11 -O2 
	g++ sub2.cpp -o sub2 -std=c++11 -O2
	g++ sub3.cpp -o sub3 -std=c++11 -O2
	g++ sub4.cpp -o sub4 -std=c++11 -O2
	g++ sub5.cpp -o sub5 -std=c++11 -O2

clean:
	-rm sub?
